language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint
  - wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.5.1%2Bcpu.zip
  - unzip libtorch-cxx11-abi-shared-with-deps-1.5.1+cpu.zip
  - sudo mv libtorch /opt
  - LD_LIBRARY_PATH=/opt/libtorch/lib:${LD_LIBRARY_PATH}
script:
  - go test -v github.com/sugarme/gotch/tensor
  - go test -v github.com/sugarme/gotch/nn
  - go test -v github.com/sugarme/gotch/vision
